version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: factchecker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  factchecker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/factchecker
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ../models:/app/models
      - ../media:/app/media
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  redis_data: